platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def install_pods
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
	  # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )
end

target 'Production' do
  install_pods
end

target 'Staging' do
  install_pods
end

target 'Development' do
  install_pods

  # Enables Flipper.
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.

  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
