platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Production' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
end

target 'Staging' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
end

target 'Development' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
  
  pre_install do |installer|
    codegen_pre_install(installer)
  end

  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
    flipper_post_install(installer)
  end
end
